# Generated by Django 2.1.4 on 2019-01-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190107_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
